# Python Libraries

## 1.Numpy 
It is called numerical python which is used for mathematical and scientific computing

In [1]:
import numpy as np

In [2]:
n1 = np.array([10,20,30,40])      #single dimensional array
n1 

array([10, 20, 30, 40])

In [3]:
type(n1)

numpy.ndarray

In [4]:
n2 = np.array([[10,20,30,40],[50,60,70,80],[90,100,110,120]])  #Multi dimensional Array
n2

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [5]:
type(n2)

numpy.ndarray

In [6]:
#Numpy array with zeros
n3 = np.zeros([1,2])
n3

array([[0., 0.]])

In [7]:
n3 = np.zeros([5,5])
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [8]:
#np full method
n4= np.full((4,4),10)
n4

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [9]:
n4.shape 

(4, 4)

In [10]:
n4.shape = (8,2)
n4

array([[10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10],
       [10, 10]])

In [11]:
#numpy array within particular range
n5= np.arange(10,20)
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [13]:
n6= np.arange(10,50,5)
n6

array([10, 15, 20, 25, 30, 35, 40, 45])

In [14]:
#np for random numbers
n7= np.random.randint(1,50,8)
n7

array([39, 12,  1, 23, 29, 23, 11,  9])

In [15]:
n7.shape

(8,)

In [16]:
#joining numpy arrays using vstack,hstack,column_stack
n1 = np.array([10,20,30])
n2 =np.array([40,50,60])

In [17]:
n3 = np.vstack((n1,n2))
n3

array([[10, 20, 30],
       [40, 50, 60]])

In [18]:
n3 = np.hstack((n1,n2))
n3

array([10, 20, 30, 40, 50, 60])

In [19]:
n3 = np.column_stack((n1,n2))
n3

array([[10, 40],
       [20, 50],
       [30, 60]])

In [20]:
#numpy intersection and differences
n1 = np.array([10,20,30,40,50,60,70])
n2 =np.array([50,60,80,90,110,120])

In [21]:
n3 = np.intersect1d(n1,n2)
n3

array([50, 60])

In [22]:
n3 = np.setdiff1d(n1,n2)
n3

array([10, 20, 30, 40, 70])

In [23]:
#addition of arrrays
n1 = np.array([10,20,30])
n2= np.array([1,2,3])

In [24]:
n3 = np.sum([n1,n2])

In [25]:
n3

66

In [26]:
n3 = np.sum([n1,n2],axis=0)  #vertical
n3

array([11, 22, 33])

In [27]:
n3 = np.sum([n1,n2],axis=1)  #horizontal
n3

array([60,  6])

In [28]:
n6 = np.array([10,20,30])
n6 = n6+1
n6

array([11, 21, 31])

In [29]:
n7= np.array([10,20,30])
n7 = n7*2
n7

array([20, 40, 60])

In [30]:
n8= np.array([10,20,30])
n8=n8-2
n8

array([ 8, 18, 28])

In [31]:
n8= np.array([10,20,30])
n8 =n8/2
n8

array([ 5., 10., 15.])

In [32]:
#mean, stdeviation, median
n= np.array([5,6,7,8,9])
n

array([5, 6, 7, 8, 9])

In [33]:
n.mean()

7.0

In [34]:
np.median(n)

7.0

In [35]:
np.std(n1)

8.16496580927726

In [36]:
#np transpose
n10 = np.array([[3,2],[5,7]])
n10

array([[3, 2],
       [5, 7]])

In [37]:
n10.transpose()

array([[3, 5],
       [2, 7]])

In [38]:
#numpy array multiplication 
n1= np.array([[1,2,3],[4,5,6],[7,8,9]])
n1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
n2= np.array([[10,20,30],[40,50,60],[70,80,90]])
n2

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [40]:
n1.dot(n2)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [41]:
#numpy array save and load

n2 = np.array([[1,2,3],[4,5,6]])
n2

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
n3 = np.save("numpyn3",n2)
n3

In [43]:
n4 = np.load("numpyn3.npy")
n4

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
type(n4)

numpy.ndarray

In [45]:
#Numpy Matrix

In [46]:
n = np.array([[1,2,3],[4,5,6],[7,8,9]])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
n[0]

array([1, 2, 3])

In [48]:
n[1]

array([4, 5, 6])

In [54]:
n[:,1]

array([2, 5, 8])

In [63]:
n[2,2]

9

In [64]:
n[2,1]

8